# Generated by Django 5.1.4 on 2025-01-09 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman', models.CharField(max_length=100, verbose_name='Komissiya raisi')),
                ('deputy', models.CharField(max_length=100, verbose_name='Rais orinbosari')),
                ('secretary', models.CharField(max_length=100, verbose_name='Komissiya kotibi')),
                ('members', models.CharField(max_length=100, verbose_name='Komissiya azolari')),
            ],
            options={
                'verbose_name': 'Comissions',
                'verbose_name_plural': 'Comissions',
            },
        ),
        migrations.CreateModel(
            name='Edutype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Talim turi',
                'verbose_name_plural': 'Talim turi',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu nomi')),
                ('order', models.CharField(max_length=100, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Sciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('directions', models.CharField(max_length=100, verbose_name='Yonalish nomi')),
            ],
            options={
                'verbose_name': 'Fan nomi',
                'verbose_name_plural': 'Fan nomi',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('directions', models.CharField(max_length=500, verbose_name='Yonalish nomi')),
                ('comission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miuz.comissions', verbose_name='Komissiya')),
                ('sciences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miuz.sciences', verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Groups',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya')),
                ('father_name', models.CharField(max_length=100, verbose_name='Otasining_ismi')),
                ('organization', models.CharField(max_length=100, verbose_name='Tashkilot_nomi')),
                ('number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon raqam to'g'ri formatda bo'lishi kerak: '+998901234567'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqami')),
                ('oak_decision', models.FileField(blank=True, null=True, upload_to='oak_decision/', verbose_name='OAK byulleteni yoki tashkilot kengashi qarori')),
                ('work_order', models.FileField(blank=True, null=True, upload_to='work_order/', verbose_name='Ish_buyrugi')),
                ('reference_letter', models.FileField(blank=True, null=True, upload_to='reference_letter/', verbose_name='Yollanma_xati')),
                ('application', models.FileField(upload_to='application/', verbose_name='Arizasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Ariza yuborilgan vaqti')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='miuz.edutype', verbose_name='Talim turi')),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='miuz.groups', verbose_name='Ixtisoslik')),
                ('sciences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='miuz.sciences', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
