# Generated by Django 4.2.19 on 2025-02-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='passed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
