# Generated by Django 4.2.19 on 2025-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuz', '0002_alter_examresult_exam_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('graded', 'Baholangan')], default='pending', max_length=20),
        ),
    ]
