# Generated by Django 4.2.19 on 2025-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuz', '0002_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
