# Generated by Django 5.1.4 on 2025-01-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuz', '0002_alter_applications_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='sciences',
        ),
        migrations.AlterField(
            model_name='sciences',
            name='directions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miuz.groups', verbose_name='Yonalish nomi'),
        ),
    ]
