# Generated by Django 4.2.18 on 2025-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miuz', '0003_remove_groups_sciences_alter_sciences_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
