"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from dotenv import load_dotenv

# .env faylini yuklash
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import environ

env = environ.Env()
environ.Env.read_env()

ONEID_CLIENT_ID = env('ONEID_CLIENT_ID')
ONEID_CLIENT_SECRET = env('ONEID_CLIENT_SECRET')
ONEID_REDIRECT_URI = env('ONEID_REDIRECT_URI')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://sso.egov.uz']

# # OneID sozlamalari
# ONEID_AUTH_URL = "https://sso.oneid.uz/oauth/authorize"
# ONEID_TOKEN_URL = "https://sso.oneid.uz/oauth/token"
# ONEID_USER_INFO_URL = "https://sso.oneid.uz/oauth/userinfo"
# ONEID_CLIENT_ID = "nuu_uz"  # OneID'dan berilgan client_id
# ONEID_CLIENT_SECRET = "F7HIY3b1B6oTJvhp49walQg5"  # OneID'dan berilgan maxfiy kalit
# ONEID_REDIRECT_URI = "httredirect_uri=https://malakaviy.nuu.uz/oneid/callback"  # OneID'da ro'yxatdan o'tgan redirect URI
# ONEID_SCOPE = "openid profile email"


#foydalanuvchini chiqarib yuborish
# Sessiya muddatini 10 daqiqaga o'rnatish (sekundlarda)
SESSION_COOKIE_AGE = 2000

# Sessiya avtomatik uzaytirilmasligi uchun
SESSION_SAVE_EVERY_REQUEST = True

# Brauzerni yopganda sessiya tugashini faollashtirish
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'miuz',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # agar Google yoki boshqa provayderlarni qo'llayotgan bo'lsangiz

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth middleware
    'allauth.account.middleware.AccountMiddleware',  # Bu qatorni qo'shing
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

INSTALLED_APPS += ['crispy_forms']
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = False  # Mahalliy vaqt zonasida saqlash uchun

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATICFILES_DIRS = [
    BASE_DIR / "config/static/"
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'  # Kirishdan so'ng foydalanuvchi qayerga o'tishini belgilash
# settings.py


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# # Kirishdan keyingi sahifa
# LOGIN_REDIRECT_URL = '/'
# # Agar foydalanuvchi tizimga kirmagan bo'lsa, login sahifasiga yo'naltirish
# LOGIN_URL = '/login/'
# LOGOUT_REDIRECT_URL = '/login/'  # Chiqishdan keyin yo'naltirish


LOGIN_REDIRECT_URL = '/redirect/'  # Tizimga kirgandan keyin yo'naltirish
LOGOUT_REDIRECT_URL = '/'  # Logoutdan keyin yo'naltirish
LOGIN_URL = '/'  # Login bo'lmagan holatda yo'naltirish